/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Array */

#ifndef _Included_Array
#define _Included_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Array
 * Method:    generate
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Array_generate
  (JNIEnv *, jobject, jint);

/*
 * Class:     Array
 * Method:    diff
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_Array_diff
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
