/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgpa */

#ifndef _Included_cgpa
#define _Included_cgpa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgpa
 * Method:    checkCGPA1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cgpa_checkCGPA1
  (JNIEnv *, jobject);

/*
 * Class:     cgpa
 * Method:    checkCGPA2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cgpa_checkCGPA2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
