/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class numArray */

#ifndef _Included_numArray
#define _Included_numArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     numArray
 * Method:    print
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_numArray_print
  (JNIEnv *, jobject, jint);

/*
 * Class:     numArray
 * Method:    diff
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_numArray_diff
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
